menu();
function menu(){
	var str='';	
	str+='<div class="row">';
		str+='<div class="col-sm-12">'
		str+='<div class="panel-group m_bottom_0" id="accordion" role="tablist" aria-multiselectable="true">';	
			str+='<div class="panel panel-default" id="menuCollapse1" role="tablist" aria-multiselectable="true">';	
				//str+='<div class="col-sm-12">';
					//str+='<div class="menu-heading-block" >';					
						//header						
						str+='<div class="panel-heading" role="tab" style="background-color: #1e92b2;">';
							str+='<a  role="button" class="collapsed panelCollapseIcon_menuIcon" data-toggle="collapse" data-parent="#accordion" href="#ruralWaterCollapse" aria-expanded="true" aria-controls="" style="color:#fff; outline: none;">';
								str+='<h4 class="text-capital">Rural Water Supply</h4>';
							str+='</a>';
						str+='</div>';
						//body					
						str+='<div id="ruralWaterCollapse" class="panel-collapse collapse " role="tabpanel" aria-labelledby="">';
							str+='<div class="panel-body">';
								str+='<div class="row">';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#56A3C5">';
											str+='<a href="ruralWaterSupplyDashBoard">';
												str+='<h3>RWS</h3>';
												str+='<p>Rural Water Supply</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#8A2BE2">';
											str+='<a href="newsArticles?deptId=2171">';
												str+='<h3>RWS News</h3>';
												str+='<p>Rural&nbsp;Water&nbsp;Supply&nbsp;News</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
								str+='</div>';
								str+='<div class="row">';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#1e92b2">';
											str+='<a href="swachhBharatMissionIHHL">';
												str+='<h3>IHHL</h3>';
												str+='<p>Swatch Bharat Mission</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#1c94ef">';
											str+='<a href="waterTanksClorinationDashBoard">';
												str+='<h3>WTC</h3>';
												str+='<p>Water Tank chlorination</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#483D8B">';
											str+='<a href="vehicleTrackingDashboard">';
												str+='<h3>VT</h3>';
												 str+='<p>Vehicle Tracking</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#59bf82">';
											str+='<a href="jalavaniAlertsDashBoard?deptId=49">';
												str+='<h3>JALAVANI</h3>';
												str+='<p>Jalavani Alert Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#EE6CA9">';
											str+='<a href="worksDashBoard">';
												str+='<h3>RWS WORKS</h3>';
												 str+='<p>RWS Works Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#ff5e1c">';
											str+='<a href="NTRSujalaDashboard">';
												str+='<h3>NTR Sujala</h3>';
												 str+='<p>NTRSujalaDashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-12 m_top10">';
										str+='<div class="menu-block" style="background-color:#2b567d;">';
											str+='<a href="assetVerificationDashBoard">';
												str+='<h3>Asset&nbspVerification</h3>';
												 str+='<p>AssetVerificationDashBoard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
								str+='</div>';						
							str+='</div>';
						str+='</div>';
					//str+='</div>';
				//str+='</div>';
			str+='</div>';		
			str+='<div class="panel panel-default" id="menuCollapse2" role="tablist" aria-multiselectable="true">';	
				//str+='<div class="col-sm-12 m_top10">';					
					//str+='<div class="menu-heading-block" >';
						//header	
						str+='<div class="panel-heading" role="tab" style="background-color: #0F685C;">';
							str+='<a  role="button" class="collapsed panelCollapseIcon_menuIcon" data-toggle="collapse" data-parent="#accordion" href="#panchayatRajCollapse" aria-expanded="true" aria-controls="" style="color:#fff; outline: none;">';
								str+='<h4 class="text-capital">PANCHAYAT RAJ</h4>';
							str+='</a>';
						str+='</div>';
						//body						
						str+='<div id="panchayatRajCollapse" class="panel-collapse collapse " role="tabpanel" aria-labelledby="">';
							str+='<div class="panel-body">';
								str+='<div class="row">';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#0F685C">';
											str+='<a href="prisDashBoard">';
												str+='<h3>PRIS</h3>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#31B8B7">';
											str+='<a href="drainDashBoard">';
												str+='<h3>DRAINS</h3>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#2C546C">';
											str+='<a href="EncDevelopmentDashboard">';
												str+='<h3>ENC</h3>';
												str+='<p>Engineering Dept</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#512507">';
											str+='<a href="getdailySpikeReport">';
												str+='<h3>SA</h3>';
												str+='<p>Spike Analysis</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#888420">';
											str+='<a href="getlightsMonitoringDashboard">';
												str+='<h3>LED</h3>';
												str+='<p>Light Monitoring</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#ff5e1c">';
											str+='<a href="solidWasteManagementDashboard">';
												str+='<h3>SWM</h3>';
												 str+='<p>Solid Waste Management</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#FF1493">';
											str+='<a href="panchayatTaxDashboard">';
												str+='<h3>Taxes</h3>';
												str+=' <p>Panchayat Raj Taxes</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#7B68EE">';
											str+='<a href="eMeetingsDashboard">';
												str+='<h3>E Meetings</h3>';
												 str+='<p>Panchayat Raj eMeetings</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#008000">';
											str+='<a href="newsArticles?deptId=2210">';
												str+='<h3>PR News</h3>';
												 str+='<p>Panchayat Raj News</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#1c94ef">';
											str+='<a href="EncWorksDashboard">';
												str+='<h3>ENC WORKS</h3>';
												 str+='<p>ENC Works DashBoard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#000">';
											str+='<a href="rurbanDashboard">';
												str+='<h3>Rurban</h3>';
												 str+='<p>RUrban Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6 m_top10">';
										str+='<div class="menu-block" style="background-color:#ff9900">';
											str+='<a href="tenStarRatingDashBoard">';
												str+='<h3>10 Star Rating</h3>';
												 str+='<p>TenStarRating Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-12 m_top10">';
										str+='<div class="menu-block" style="background-color:#2A8074">';
											str+='<a href="ohsrDashboard">';
												str+='<h3>SWACHH DHARA</h3>';
												 str+='<p>SWACHH DHARA Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
								str+='</div>';							
							str+='</div>';
						str+='</div>';
					//str+='</div>';				
				//str+='</div>';
			str+='</div>';
			str+='<div class="panel panel-default" id="menuCollapse3" role="tablist" aria-multiselectable="true">';	
				//str+='<div class="col-sm-12 m_top10">';	
					//str+='<div class="menu-heading-block" >';	
						//header
						str+='<div class="panel-heading" role="tab" style="background-color: #88186B;">';													
							str+='<a  role="button" class="collapsed panelCollapseIcon_menuIcon" data-toggle="collapse" data-parent="#accordion" href="#ruralDevelopmentCollapse" aria-expanded="true" aria-controls="" style="color:#fff; outline: none;">';
								str+='<h4 class="text-capital">RURAL DEVELOPMENT</h4>';
							str+='</a>';
						str+='</div>';
						//body					
						str+='<div id="ruralDevelopmentCollapse" class="panel-collapse collapse " role="tabpanel" aria-labelledby="">';	
							str+='<div class="panel-body">';
								str+='<div class="row">';
									str+='<div class="col-sm-12 m_top10">';
										str+='<div class="menu-block" style="background-color:#88186B">';
											str+='<a href="MGNREGSDashboard">';
												str+='<h3>MGNREGS</h3>';
												str+='<p>Mahatma Gandhi Rural employement guarantee scheme</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-12 m_top10">';
									str+='<div class="row">';
									str+='<div class="col-sm-6">';
										str+='<div class="menu-block" style="background-color:#ff1c5e">';
											str+='<a href="RuralDevelopmentDashboard">';
												str+='<h3>RD</h3>';
												str+='<p>Rural&nbsp;Development&nbsp;Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-6">';
										str+='<div class="menu-block" style="background-color:#8B0000">';
											str+='<a href="newsArticles?deptId=2170">';
												str+='<h3>RD News</h3>';
												str+='<p>Rural Development News</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
									str+='</div>';
									str+='</div>';
									str+='<div class="col-sm-12 m_top10">';
										str+='<div class="menu-block" style="background-color:#0590d4">';
											str+='<a href="statetoStateComparisionDashboard">';
												str+='<h3>State Comparision</h3>';
												str+='<p>State to State Comparision Dashboard</p>';
											str+='</a>';
										str+='</div>';
									str+='</div>';
								str+='</div>';							
							str+='</div>';
						str+='</div>';
					//str+='</div>';				
				//str+='</div>';
			str+='</div>';
		str+='</div>';
		str+='</div>';
	str+='</div>';	
	$("#menu").html(str);
}
/* $("header").on("click",".menu-cls",function(e){
	e.stopPropagation();
	$(".menu-data-cls").toggle();
});

$(document).on("click",function(){
	$(".menu-data-cls").hide();
}); */
$(document).on("click",".menu-block",function(){
	$(".menu-data-cls").hide();
});
$(document).on("click","#accordion",function(e){
	e.stopPropagation();	
})